void defineHashMapDefinition(string fromType = "", string toType = "", string defaultReturnValue = "", string nameSuffix = ""){
    string returnStatementToUse = (defaultReturnValue == "") ? getDefaultReturnStatement(toType) : ("return " + defaultReturnValue + ";");
    code("class "+getTypeTitle(fromType)+"To"+getTypeTitle(toType)+nameSuffix+"HashMap {");
        code("bool initialised = false;");
        code("int capacity = 16;");
        code("int count = 0;");
        code("bool[] occupied = default;");
        code(fromType+"[] keys = default;");
        code(toType+"[] values = default;");
        code("");
        code("// Cache fields");
        code(fromType+"[] cachedKeys = default;");
        code(toType+"[] cachedValues = default;");
        code("bool cacheValid = false;");
        code("");
        code("void invalidateCache(){");
            code("cacheValid = false;");
        code("}");
        code("");
        code("void initialise(){");
            code("occupied = new bool(capacity, false);");
            code("keys = new "+fromType+"(capacity"+getArrayDefaultValue(fromType)+");");
            code("values = new "+toType+"(capacity"+getArrayDefaultValue(toType)+");");
            code("initialised = true;");
            code("invalidateCache();");
        code("}");
        code("");
        code("int hash("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            if (fromType == "string") {
                code("int keyInt = kbGetAnimationID(key);");
            } else if (fromType == "bool") {
                code("int keyInt = 0;");
                code("if(key){ keyInt = 1; }");
            } else {
                code("int keyInt = key;");
            }
            code("int h = (keyInt ^ (keyInt >> 16)) * 73244539;");
            code("if(h < 0){");
                code("h = 0 - h;");
            code("}");
            code("return h % capacity;");
        code("}");
        code("");
        code("int findSlot("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            code("int slot = hash(key);");
            code("for(int i = 0; i < capacity; i++){");
                code("if(!occupied[slot]){");
                    code("return slot;");
                code("}");
                code("if(keys[slot] == key){");
                    code("return slot;");
                code("}");
                code("slot = slot + 1;");
                code("if(slot >= capacity){");
                    code("slot = 0;");
                code("}");
            code("}");
            code("return -1;");
        code("}");
        code("");
        code("void resize(){");
            code("int oldCapacity = capacity;");
            code("bool[] oldOccupied = occupied;");
            code(fromType+"[] oldKeys = keys;");
            code(toType+"[] oldValues = values;");
            code("");
            code("capacity = capacity * 2;");
            code("occupied = new bool(capacity, false);");
            code("keys = new "+fromType+"(capacity"+getArrayDefaultValue(fromType)+");");
            code("values = new "+toType+"(capacity"+getArrayDefaultValue(toType)+");");
            code("count = 0;");
            code("");
            code("for(int i = 0; i < oldCapacity; i++){");
                code("if(oldOccupied[i]){");
                    code("int slot = findSlot(oldKeys[i]);");
                    code("if(slot >= 0){");
                        code("occupied[slot] = true;");
                        code("keys[slot] = oldKeys[i];");
                        code("values[slot] = oldValues[i];");
                        code("count++;");
                    code("}");
                code("}");
            code("}");
            code("invalidateCache();");
        code("}");
        code("");
        code(""+toType+" put("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+", "+getParamQualifier(toType)+" value"+getVariableDefaultValue(toType)+"){");
            code("if(!initialised){");
                code("initialise();");
            code("}");
            code("if(count * 10 >= capacity * 7){");
                code("resize();");
            code("}");
            code("int slot = findSlot(key);");
            code("if(slot == -1){");
                code(returnStatementToUse);
            code("}");
            code("if(occupied[slot]){");
                code(""+toType+" previous = values[slot];");
                code("values[slot] = value;");
                code("invalidateCache();");
                code("return previous;");
            code("}");
            code("occupied[slot] = true;");
            code("keys[slot] = key;");
            code("values[slot] = value;");
            code("count++;");
            code("invalidateCache();");
            code(returnStatementToUse);
        code("}");
        code("");
        code(""+toType+" get("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            code("if(!initialised){");
                code(returnStatementToUse);
            code("}");
            code("int slot = findSlot(key);");
            code("if(slot == -1){");
                code(returnStatementToUse);
            code("}");
            code("if(!occupied[slot]){");
                code(returnStatementToUse);
            code("}");
            code("return values[slot];");
        code("}");
        code("");
        code(""+toType+" remove("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            code("if(!initialised){");
                code(returnStatementToUse);
            code("}");
            code("int slot = findSlot(key);");
            code("if(slot == -1){");
                code(returnStatementToUse);
            code("}");
            code("if(!occupied[slot]){");
                code(returnStatementToUse);
            code("}");
            code(""+toType+" removed = values[slot];");
            code("occupied[slot] = false;");
            code("count--;");
            code("invalidateCache();");
            code("");
            code("int nextSlot = slot + 1;");
            code("if(nextSlot >= capacity){");
                code("nextSlot = 0;");
            code("}");
            code("while(occupied[nextSlot]){");
                code(fromType+" rehashKey = keys[nextSlot];");
                code(toType+" rehashValue = values[nextSlot];");
                code("occupied[nextSlot] = false;");
                code("count--;");
                code("int targetSlot = findSlot(rehashKey);");
                code("if(targetSlot >= 0){");
                    code("occupied[targetSlot] = true;");
                    code("keys[targetSlot] = rehashKey;");
                    code("values[targetSlot] = rehashValue;");
                    code("count++;");
                code("}");
                code("nextSlot = nextSlot + 1;");
                code("if(nextSlot >= capacity){");
                    code("nextSlot = 0;");
                code("}");
            code("}");
            code("return removed;");
        code("}");
        code("");
        code("int size(){");
            code("return count;");
        code("}");
        code("");
        code("void clear(){");
            code("if(!initialised){");
                code("return;");
            code("}");
            code("for(int i = 0; i < capacity; i++){");
                code("occupied[i] = false;");
            code("}");
            code("count = 0;");
            code("invalidateCache();");
        code("}");
        code("");
        code("void buildCache(){");
            code("cachedKeys = new "+fromType+"(count"+getArrayDefaultValue(fromType)+");");
            code("cachedValues = new "+toType+"(count"+getArrayDefaultValue(toType)+");");
            code("int index = 0;");
            code("for(int i = 0; i < capacity; i++){");
                code("if(occupied[i]){");
                    code("cachedKeys[index] = keys[i];");
                    code("cachedValues[index] = values[i];");
                    code("index++;");
                code("}");
            code("}");
            code("cacheValid = true;");
        code("}");
        code("");
        code(fromType+"[] getKeys(){");
            code("if(!initialised || count == 0){");
                code("return new "+fromType+"(0"+getArrayDefaultValue(fromType)+");");
            code("}");
            code("if(!cacheValid){");
                code("buildCache();");
            code("}");
            code("return cachedKeys;");
        code("}");
        code("");
        code(toType+"[] getValues(){");
            code("if(!initialised || count == 0){");
                code("return new "+toType+"(0"+getArrayDefaultValue(toType)+");");
            code("}");
            code("if(!cacheValid){");
                code("buildCache();");
            code("}");
            code("return cachedValues;");
        code("}");
    code("};");
}