void defineSetDefinition(string elemType = "", string nameSuffix = ""){
    rmTriggerAddScriptLine("class "+getTypeTitle(elemType)+nameSuffix+"Set {");
        rmTriggerAddScriptLine("bool initialised = false;");
        rmTriggerAddScriptLine("int capacity = 16;");
        rmTriggerAddScriptLine("int count = 0;");
        rmTriggerAddScriptLine("bool[] occupied = default;");
        rmTriggerAddScriptLine(elemType+"[] elements = default;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("// Cache fields");
        rmTriggerAddScriptLine(elemType+"[] cachedElements = default;");
        rmTriggerAddScriptLine("bool cacheValid = false;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void invalidateCache(){");
            rmTriggerAddScriptLine("cacheValid = false;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void initialise(){");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("elements = new "+elemType+"(capacity"+getArrayDefaultValue(elemType)+");");
            rmTriggerAddScriptLine("initialised = true;");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int hash("+getParamQualifier(elemType)+" elem"+getVariableDefaultValue(elemType)+"){");
            if (elemType == "string") {
                rmTriggerAddScriptLine("int keyInt = kbGetAnimationID(elem);");
            } else if (elemType == "bool") {
                rmTriggerAddScriptLine("int keyInt = 0;");
                rmTriggerAddScriptLine("if(elem == true){ keyInt = 1; }");
            } else if (elemType == "int") {
                rmTriggerAddScriptLine("int keyInt = elem;");
            } else {
                rmTriggerAddScriptLine("int keyInt = elem.m_uuid; // Class instance unique identifier");
            }
            rmTriggerAddScriptLine("int h = (keyInt ^ (keyInt >> 16)) * 73244539;");
            rmTriggerAddScriptLine("if(h < 0){ h = 0 - h; }");
            rmTriggerAddScriptLine("int slot = h % capacity;");
            rmTriggerAddScriptLine("if(slot < 0){ slot = slot + capacity; }");
            rmTriggerAddScriptLine("return slot;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int findSlot("+getParamQualifier(elemType)+" elem"+getVariableDefaultValue(elemType)+"){");
            rmTriggerAddScriptLine("int slot = hash(elem);");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(occupied[slot] == false){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("if(elements[slot] == elem){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("slot = slot + 1;");
                rmTriggerAddScriptLine("if(slot >= capacity){");
                    rmTriggerAddScriptLine("slot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return -1;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void resize(int newCapacity = 16){");
            rmTriggerAddScriptLine("int oldCapacity = capacity;");
            rmTriggerAddScriptLine("bool[] oldOccupied = occupied;");
            rmTriggerAddScriptLine(elemType+"[] oldElements = elements;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("capacity = newCapacity;");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("elements = new "+elemType+"(capacity"+getArrayDefaultValue(elemType)+");");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("for(int i = 0; i < oldCapacity; i++){");
                rmTriggerAddScriptLine("if(oldOccupied[i] == true){");
                    rmTriggerAddScriptLine("int slot = findSlot(oldElements[i]);");
                    rmTriggerAddScriptLine("if(slot >= 0){");
                        rmTriggerAddScriptLine("occupied[slot] = true;");
                        rmTriggerAddScriptLine("elements[slot] = oldElements[i];");
                        rmTriggerAddScriptLine("count++;");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool add("+getParamQualifier(elemType)+" elem"+getVariableDefaultValue(elemType)+"){");
            rmTriggerAddScriptLine("if(initialised == false){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(count * 10 >= capacity * 7){");
                rmTriggerAddScriptLine("resize(capacity * 2);");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(elem);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(occupied[slot] == true){");
                rmTriggerAddScriptLine("return false; // Already present");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = true;");
            rmTriggerAddScriptLine("elements[slot] = elem;");
            rmTriggerAddScriptLine("count++;");
            rmTriggerAddScriptLine("invalidateCache();");
            rmTriggerAddScriptLine("return true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool contains("+getParamQualifier(elemType)+" elem"+getVariableDefaultValue(elemType)+"){");
            rmTriggerAddScriptLine("if(initialised == false || count == 0){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(elem);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return occupied[slot];");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool remove("+getParamQualifier(elemType)+" elem"+getVariableDefaultValue(elemType)+"){");
            rmTriggerAddScriptLine("if(initialised == false || count == 0){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(elem);");
            rmTriggerAddScriptLine("if(slot == -1 || occupied[slot] == false){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = false;");
            rmTriggerAddScriptLine("count--;");
            rmTriggerAddScriptLine("invalidateCache();");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("int nextSlot = slot + 1;");
            rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                rmTriggerAddScriptLine("nextSlot = 0;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("while(occupied[nextSlot] == true){");
                rmTriggerAddScriptLine(elemType+" rehashElem = elements[nextSlot];");
                rmTriggerAddScriptLine("occupied[nextSlot] = false;");
                rmTriggerAddScriptLine("int targetSlot = findSlot(rehashElem);");
                rmTriggerAddScriptLine("if(targetSlot >= 0){");
                    rmTriggerAddScriptLine("occupied[targetSlot] = true;");
                    rmTriggerAddScriptLine("elements[targetSlot] = rehashElem;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("nextSlot = nextSlot + 1;");
                rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                    rmTriggerAddScriptLine("nextSlot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("if(capacity > 16 && (capacity - count) >= (count * 10)){");
                rmTriggerAddScriptLine("resize(capacity / 2);");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("return true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int size(){");
            rmTriggerAddScriptLine("return count;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void clear(){");
            rmTriggerAddScriptLine("if(initialised == false){");
                rmTriggerAddScriptLine("return;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("occupied[i] = false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void buildCache(){");
            rmTriggerAddScriptLine("cachedElements = new "+elemType+"(count"+getArrayDefaultValue(elemType)+");");
            rmTriggerAddScriptLine("int index = 0;");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(occupied[i] == true){");
                    rmTriggerAddScriptLine("cachedElements[index] = elements[i];");
                    rmTriggerAddScriptLine("index++;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("cacheValid = true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(elemType+"[] getElements(){");
            rmTriggerAddScriptLine("if(initialised == false || count == 0){");
                rmTriggerAddScriptLine("return new "+elemType+"(0"+getArrayDefaultValue(elemType)+");");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(cacheValid == false){");
                rmTriggerAddScriptLine("buildCache();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return cachedElements;");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("};");
}