void defineHashMapDefinition(string fromType = "", string toType = "", string defaultReturnValue = "", string nameSuffix = ""){
    string returnStatementToUse = (defaultReturnValue == "") ? getDefaultReturnStatement(toType) : ("return " + defaultReturnValue + ";");
    rmTriggerAddScriptLine("class "+getTypeTitle(fromType)+"To"+getTypeTitle(toType)+nameSuffix+"HashMap {");
        rmTriggerAddScriptLine("bool initialised = false;");
        rmTriggerAddScriptLine("int capacity = 16;");
        rmTriggerAddScriptLine("int count = 0;");
        rmTriggerAddScriptLine("bool[] occupied = default;");
        rmTriggerAddScriptLine(fromType+"[] keys = default;");
        rmTriggerAddScriptLine(toType+"[] values = default;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("// Cache fields");
        rmTriggerAddScriptLine(fromType+"[] cachedKeys = default;");
        rmTriggerAddScriptLine(toType+"[] cachedValues = default;");
        rmTriggerAddScriptLine("bool cacheValid = false;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void invalidateCache(){");
            rmTriggerAddScriptLine("cacheValid = false;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void initialise(){");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("keys = new "+fromType+"(capacity"+getArrayDefaultValue(fromType)+");");
            rmTriggerAddScriptLine("values = new "+toType+"(capacity"+getArrayDefaultValue(toType)+");");
            rmTriggerAddScriptLine("initialised = true;");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int hash("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            if (fromType == "string") {
                rmTriggerAddScriptLine("int keyInt = kbGetAnimationID(key);");
            } else if (fromType == "bool") {
                rmTriggerAddScriptLine("int keyInt = 0;");
                rmTriggerAddScriptLine("if(key){ keyInt = 1; }");
            } else {
                rmTriggerAddScriptLine("int keyInt = key;");
            }
            rmTriggerAddScriptLine("int h = (keyInt ^ (keyInt >> 16)) * 73244539;");
            rmTriggerAddScriptLine("if(h < 0){");
                rmTriggerAddScriptLine("h = 0 - h;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return h % capacity;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int findSlot("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            rmTriggerAddScriptLine("int slot = hash(key);");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(!occupied[slot]){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("if(keys[slot] == key){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("slot = slot + 1;");
                rmTriggerAddScriptLine("if(slot >= capacity){");
                    rmTriggerAddScriptLine("slot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return -1;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void resize(){");
            rmTriggerAddScriptLine("int oldCapacity = capacity;");
            rmTriggerAddScriptLine("bool[] oldOccupied = occupied;");
            rmTriggerAddScriptLine(fromType+"[] oldKeys = keys;");
            rmTriggerAddScriptLine(toType+"[] oldValues = values;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("capacity = capacity * 2;");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("keys = new "+fromType+"(capacity"+getArrayDefaultValue(fromType)+");");
            rmTriggerAddScriptLine("values = new "+toType+"(capacity"+getArrayDefaultValue(toType)+");");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("for(int i = 0; i < oldCapacity; i++){");
                rmTriggerAddScriptLine("if(oldOccupied[i]){");
                    rmTriggerAddScriptLine("int slot = findSlot(oldKeys[i]);");
                    rmTriggerAddScriptLine("if(slot >= 0){");
                        rmTriggerAddScriptLine("occupied[slot] = true;");
                        rmTriggerAddScriptLine("keys[slot] = oldKeys[i];");
                        rmTriggerAddScriptLine("values[slot] = oldValues[i];");
                        rmTriggerAddScriptLine("count++;");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(""+toType+" put("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+", "+getParamQualifier(toType)+" value"+getVariableDefaultValue(toType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(count * 10 >= capacity * 7){");
                rmTriggerAddScriptLine("resize();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(key);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(occupied[slot]){");
                rmTriggerAddScriptLine(""+toType+" previous = values[slot];");
                rmTriggerAddScriptLine("values[slot] = value;");
                rmTriggerAddScriptLine("invalidateCache();");
                rmTriggerAddScriptLine("return previous;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = true;");
            rmTriggerAddScriptLine("keys[slot] = key;");
            rmTriggerAddScriptLine("values[slot] = value;");
            rmTriggerAddScriptLine("count++;");
            rmTriggerAddScriptLine("invalidateCache();");
            rmTriggerAddScriptLine(returnStatementToUse);
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(""+toType+" get("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(key);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!occupied[slot]){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return values[slot];");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(""+toType+" remove("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(key);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!occupied[slot]){");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine(""+toType+" removed = values[slot];");
            rmTriggerAddScriptLine("occupied[slot] = false;");
            rmTriggerAddScriptLine("count--;");
            rmTriggerAddScriptLine("invalidateCache();");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("int nextSlot = slot + 1;");
            rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                rmTriggerAddScriptLine("nextSlot = 0;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("while(occupied[nextSlot]){");
                rmTriggerAddScriptLine(fromType+" rehashKey = keys[nextSlot];");
                rmTriggerAddScriptLine(toType+" rehashValue = values[nextSlot];");
                rmTriggerAddScriptLine("occupied[nextSlot] = false;");
                rmTriggerAddScriptLine("count--;");
                rmTriggerAddScriptLine("int targetSlot = findSlot(rehashKey);");
                rmTriggerAddScriptLine("if(targetSlot >= 0){");
                    rmTriggerAddScriptLine("occupied[targetSlot] = true;");
                    rmTriggerAddScriptLine("keys[targetSlot] = rehashKey;");
                    rmTriggerAddScriptLine("values[targetSlot] = rehashValue;");
                    rmTriggerAddScriptLine("count++;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("nextSlot = nextSlot + 1;");
                rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                    rmTriggerAddScriptLine("nextSlot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return removed;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int size(){");
            rmTriggerAddScriptLine("return count;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void clear(){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("occupied[i] = false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void buildCache(){");
            rmTriggerAddScriptLine("cachedKeys = new "+fromType+"(count"+getArrayDefaultValue(fromType)+");");
            rmTriggerAddScriptLine("cachedValues = new "+toType+"(count"+getArrayDefaultValue(toType)+");");
            rmTriggerAddScriptLine("int index = 0;");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(occupied[i]){");
                    rmTriggerAddScriptLine("cachedKeys[index] = keys[i];");
                    rmTriggerAddScriptLine("cachedValues[index] = values[i];");
                    rmTriggerAddScriptLine("index++;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("cacheValid = true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(fromType+"[] getKeys(){");
            rmTriggerAddScriptLine("if(!initialised || count == 0){");
                rmTriggerAddScriptLine("return new "+fromType+"(0"+getArrayDefaultValue(fromType)+");");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!cacheValid){");
                rmTriggerAddScriptLine("buildCache();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return cachedKeys;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(toType+"[] getValues(){");
            rmTriggerAddScriptLine("if(!initialised || count == 0){");
                rmTriggerAddScriptLine("return new "+toType+"(0"+getArrayDefaultValue(toType)+");");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!cacheValid){");
                rmTriggerAddScriptLine("buildCache();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return cachedValues;");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("};");
}