void defineHashSetDefinition(string itemType = "", string nameSuffix = ""){
    rmTriggerAddScriptLine("class "+getTypeTitle(itemType)+"HashSet"+nameSuffix+" {");
        rmTriggerAddScriptLine("bool initialised = false;");
        rmTriggerAddScriptLine("int capacity = 16;");
        rmTriggerAddScriptLine("int count = 0;");
        rmTriggerAddScriptLine("bool[] occupied = default;");
        rmTriggerAddScriptLine(itemType+"[] items = default;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("// Cache fields");
        rmTriggerAddScriptLine(itemType+"[] cachedValues = default;");
        rmTriggerAddScriptLine("bool cacheValid = false;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void invalidateCache(){");
            rmTriggerAddScriptLine("cacheValid = false;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void initialise(){");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("items = new "+itemType+"(capacity"+getArrayDefaultValue(itemType)+");");
            rmTriggerAddScriptLine("initialised = true;");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int hash("+getParamQualifier(itemType)+" item"+getVariableDefaultValue(itemType)+"){");
            if (itemType == "string") {
                rmTriggerAddScriptLine("int keyInt = kbGetAnimationID(item);");
            } else if (itemType == "bool") {
                rmTriggerAddScriptLine("int keyInt = 0;");
                rmTriggerAddScriptLine("if(item){ keyInt = 1; }");
            } else if (itemType == "int" || itemType == "float") {
                rmTriggerAddScriptLine("int keyInt = item;");
            } else {
                rmTriggerAddScriptLine("int keyInt = item.m_uuid;");
            }
            rmTriggerAddScriptLine("int h = (keyInt ^ (keyInt >> 16)) * 73244539;");
            rmTriggerAddScriptLine("if(h < 0){");
                rmTriggerAddScriptLine("h = 0 - h;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return h % capacity;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int findSlot("+getParamQualifier(itemType)+" item"+getVariableDefaultValue(itemType)+"){");
            rmTriggerAddScriptLine("int slot = hash(item);");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(!occupied[slot]){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                if (itemType == "string" || itemType == "bool" || itemType == "int" || itemType == "float") {
                    rmTriggerAddScriptLine("if(items[slot] == item){");
                } else {
                    rmTriggerAddScriptLine(itemType+" currentItem = items[slot];");
                    rmTriggerAddScriptLine("if(currentItem.m_uuid == item.m_uuid){");
                }
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("slot = slot + 1;");
                rmTriggerAddScriptLine("if(slot >= capacity){");
                    rmTriggerAddScriptLine("slot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return -1;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void resize(){");
            rmTriggerAddScriptLine("int oldCapacity = capacity;");
            rmTriggerAddScriptLine("bool[] oldOccupied = occupied;");
            rmTriggerAddScriptLine(itemType+"[] oldItems = items;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("capacity = capacity * 2;");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("items = new "+itemType+"(capacity"+getArrayDefaultValue(itemType)+");");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("for(int i = 0; i < oldCapacity; i++){");
                rmTriggerAddScriptLine("if(oldOccupied[i]){");
                    rmTriggerAddScriptLine(itemType+" oldItem = oldItems[i];");
                    rmTriggerAddScriptLine("int slot = findSlot(oldItem);");
                    rmTriggerAddScriptLine("if(slot >= 0){");
                        rmTriggerAddScriptLine("occupied[slot] = true;");
                        rmTriggerAddScriptLine("items[slot] = oldItem;");
                        rmTriggerAddScriptLine("count++;");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool add("+getParamQualifier(itemType)+" item"+getVariableDefaultValue(itemType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(count * 10 >= capacity * 7){");
                rmTriggerAddScriptLine("resize();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(item);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(occupied[slot]){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = true;");
            rmTriggerAddScriptLine("items[slot] = item;");
            rmTriggerAddScriptLine("count++;");
            rmTriggerAddScriptLine("invalidateCache();");
            rmTriggerAddScriptLine("return true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool contains("+getParamQualifier(itemType)+" item"+getVariableDefaultValue(itemType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(item);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return occupied[slot];");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool remove("+getParamQualifier(itemType)+" item"+getVariableDefaultValue(itemType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(item);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!occupied[slot]){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = false;");
            rmTriggerAddScriptLine("count--;");
            rmTriggerAddScriptLine("invalidateCache();");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("int nextSlot = slot + 1;");
            rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                rmTriggerAddScriptLine("nextSlot = 0;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("while(occupied[nextSlot]){");
                rmTriggerAddScriptLine(itemType+" rehashItem = items[nextSlot];");
                rmTriggerAddScriptLine("occupied[nextSlot] = false;");
                rmTriggerAddScriptLine("count--;");
                rmTriggerAddScriptLine("int targetSlot = findSlot(rehashItem);");
                rmTriggerAddScriptLine("if(targetSlot >= 0){");
                    rmTriggerAddScriptLine("occupied[targetSlot] = true;");
                    rmTriggerAddScriptLine("items[targetSlot] = rehashItem;");
                    rmTriggerAddScriptLine("count++;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("nextSlot = nextSlot + 1;");
                rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                    rmTriggerAddScriptLine("nextSlot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int size(){");
            rmTriggerAddScriptLine("return count;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void clear(){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("occupied[i] = false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("invalidateCache();");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void buildCache(){");
            rmTriggerAddScriptLine("cachedValues = new "+itemType+"(count"+getArrayDefaultValue(itemType)+");");
            rmTriggerAddScriptLine("int index = 0;");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(occupied[i]){");
                    rmTriggerAddScriptLine("cachedValues[index] = items[i];");
                    rmTriggerAddScriptLine("index++;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("cacheValid = true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(itemType+"[] getValues(){");
            rmTriggerAddScriptLine("if(!initialised || count == 0){");
                rmTriggerAddScriptLine("return new "+itemType+"(0"+getArrayDefaultValue(itemType)+");");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!cacheValid){");
                rmTriggerAddScriptLine("buildCache();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return cachedValues;");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("};");
}