void defineHashMapDefinition(string fromType = "", string toType = "", string defaultReturnValue = "", string nameSuffix = ""){
    string returnStatementToUse = (defaultReturnValue == "") ? getDefaultReturnStatement(toType) : ("return " + defaultReturnValue + ";");
    rmTriggerAddScriptLine("class "+getTypeTitle(fromType)+"To"+getTypeTitle(toType)+nameSuffix+"HashMap {");
        rmTriggerAddScriptLine("bool initialised = false;");
        rmTriggerAddScriptLine("int count = 0;");
        rmTriggerAddScriptLine(fromType+"[] keys = default;");
        rmTriggerAddScriptLine(toType+"[] values = default;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void initialise(){");
            rmTriggerAddScriptLine("keys = new "+fromType+"(10"+getArrayDefaultValue(fromType)+");");
            rmTriggerAddScriptLine("values = new "+toType+"(10"+getArrayDefaultValue(toType)+");");
            rmTriggerAddScriptLine("initialised = true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int findIndex("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("for(int i = 0; i < count; i++){");
                rmTriggerAddScriptLine("if(keys[i] == key){");
                    rmTriggerAddScriptLine("return i;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return -1;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(""+toType+" put("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+", "+getParamQualifier(toType)+" value"+getVariableDefaultValue(toType)+"){");
            rmTriggerAddScriptLine("int index = findIndex(key);");
            rmTriggerAddScriptLine("if(index == -1){");
                rmTriggerAddScriptLine("if(count == keys.size()){");
                    rmTriggerAddScriptLine("keys.resize(2 * count"+getArrayDefaultValue(fromType)+");");
                    rmTriggerAddScriptLine("values.resize(2 * count"+getArrayDefaultValue(toType)+");");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("keys[count] = key;");
                rmTriggerAddScriptLine("values[count] = value;");
                rmTriggerAddScriptLine("count++;");
                rmTriggerAddScriptLine(returnStatementToUse);
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine(""+toType+" previous = values[index];");
            rmTriggerAddScriptLine("values[index] = value;");
            rmTriggerAddScriptLine("return previous;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(""+toType+" get("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            rmTriggerAddScriptLine("int index = findIndex(key);");
            rmTriggerAddScriptLine("if(index >= 0){");
                rmTriggerAddScriptLine("return values[index];");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine(returnStatementToUse);
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(""+toType+" remove("+getParamQualifier(fromType)+" key"+getVariableDefaultValue(fromType)+"){");
            rmTriggerAddScriptLine("int index = findIndex(key);");
            rmTriggerAddScriptLine("if(index >= 0){");
                rmTriggerAddScriptLine(""+toType+" removed = values[index];");
                rmTriggerAddScriptLine("count--;");
                rmTriggerAddScriptLine("keys[index] = keys[count];");
                rmTriggerAddScriptLine("values[index] = values[count];");
                rmTriggerAddScriptLine("return removed;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine(returnStatementToUse);
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void clear(){");
            rmTriggerAddScriptLine("count = 0;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(fromType+"[] getKeys(){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine(fromType+"[] activeKeys = new "+fromType+"(count"+getArrayDefaultValue(fromType)+");");
            rmTriggerAddScriptLine("for(int i = 0; i < count; i++){");
                rmTriggerAddScriptLine("activeKeys[i] = keys[i];");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return activeKeys;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine(toType+"[] getValues(){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine(toType+"[] activeValues = new "+toType+"(count"+getArrayDefaultValue(toType)+");");
            rmTriggerAddScriptLine("for(int i = 0; i < count; i++){");
                rmTriggerAddScriptLine("activeValues[i] = values[i];");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return activeValues;");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("};");
}