void defineHashSetDefinition(string type = "", string nameSuffix = ""){
    code("class "+getTypeTitle(type)+nameSuffix+"HashSet {");
        code("bool initialised = false;");
        code("int capacity = 16;");
        code("int count = 0;");
        code("bool[] occupied = default;");
        code(type+"[] keys = default;");
        code("");
        code("void initialise(){");
            code("occupied = new bool(capacity, false);");
            code("keys = new "+type+"(capacity"+getArrayDefaultValue(type)+");");
            code("initialised = true;");
        code("}");
        code("");
        code("int hash("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            if (type == "string") {
                code("int keyInt = kbGetAnimationID(value);");
            } else if (type == "float") {
                code("int keyInt = (int)value;");
            } else {
                code("int keyInt = (int)value;");
            }
            code("int h = keyInt * 7324451;");
            code("if(h < 0){");
                code("h = 0 - h;");
            code("}");
            code("return h % capacity;");
        code("}");
        code("");
        code("int findSlot("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            code("int slot = hash(value);");
            code("for(int i = 0; i < capacity; i++){");
                code("if(!occupied[slot]){");
                    code("return slot;");
                code("}");
                code("if(keys[slot] == value){");
                    code("return slot;");
                code("}");
                code("slot = slot + 1;");
                code("if(slot >= capacity){");
                    code("slot = 0;");
                code("}");
            code("}");
            code("return -1;");
        code("}");
        code("");
        code("void resize(){");
            code("int oldCapacity = capacity;");
            code("bool[] oldOccupied = occupied;");
            code(type+"[] oldKeys = keys;");
            code("");
            code("capacity = capacity * 2;");
            code("occupied = new bool(capacity, false);");
            code("keys = new "+type+"(capacity"+getArrayDefaultValue(type)+");");
            code("count = 0;");
            code("");
            code("for(int i = 0; i < oldCapacity; i++){");
                code("if(oldOccupied[i]){");
                    code("int slot = findSlot(oldKeys[i]);");
                    code("if(slot >= 0){");
                        code("occupied[slot] = true;");
                        code("keys[slot] = oldKeys[i];");
                        code("count++;");
                    code("}");
                code("}");
            code("}");
        code("}");
        code("");
        code("bool contains("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            code("if(!initialised){");
                code("return false;");
            code("}");
            code("int slot = findSlot(value);");
            code("if(slot == -1){");
                code("return false;");
            code("}");
            code("if(!occupied[slot]){");
                code("return false;");
            code("}");
            code("return keys[slot] == value;");
        code("}");
        code("");
        code("bool add("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            code("if(!initialised){");
                code("initialise();");
            code("}");
            code("if(count * 10 >= capacity * 7){");
                code("resize();");
            code("}");
            code("int slot = findSlot(value);");
            code("if(slot == -1){");
                code("return false;");
            code("}");
            code("if(occupied[slot]){");
                code("return false;");
            code("}");
            code("occupied[slot] = true;");
            code("keys[slot] = value;");
            code("count++;");
            code("return true;");
        code("}");
        code("");
        code("bool remove("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            code("if(!initialised){");
                code("return false;");
            code("}");
            code("int slot = findSlot(value);");
            code("if(slot == -1){");
                code("return false;");
            code("}");
            code("if(!occupied[slot]){");
                code("return false;");
            code("}");
            code("occupied[slot] = false;");
            code("count--;");
            code("");
            code("int nextSlot = slot + 1;");
            code("if(nextSlot >= capacity){");
                code("nextSlot = 0;");
            code("}");
            code("while(occupied[nextSlot]){");
                code(type+" rehashValue = keys[nextSlot];");
                code("occupied[nextSlot] = false;");
                code("count--;");
                code("int targetSlot = findSlot(rehashValue);");
                code("if(targetSlot >= 0){");
                    code("occupied[targetSlot] = true;");
                    code("keys[targetSlot] = rehashValue;");
                    code("count++;");
                code("}");
                code("nextSlot = nextSlot + 1;");
                code("if(nextSlot >= capacity){");
                    code("nextSlot = 0;");
                code("}");
            code("}");
            code("return true;");
        code("}");
        code("");
        code("int size(){");
            code("return count;");
        code("}");
        code("");
        code("void clear(){");
            code("if(!initialised){");
                code("return;");
            code("}");
            code("for(int i = 0; i < capacity; i++){");
                code("occupied[i] = false;");
            code("}");
            code("count = 0;");
        code("}");
    code("};");
}