void defineHashSetDefinition(string type = "", string nameSuffix = ""){
    rmTriggerAddScriptLine("class "+getTypeTitle(type)+nameSuffix+"HashSet {");
        rmTriggerAddScriptLine("bool initialised = false;");
        rmTriggerAddScriptLine("int capacity = 16;");
        rmTriggerAddScriptLine("int count = 0;");
        rmTriggerAddScriptLine("bool[] occupied = default;");
        rmTriggerAddScriptLine(type+"[] keys = default;");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void initialise(){");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("keys = new "+type+"(capacity"+getArrayDefaultValue(type)+");");
            rmTriggerAddScriptLine("initialised = true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int hash("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            if (type == "string") {
                rmTriggerAddScriptLine("int keyInt = kbGetAnimationID(value);");
            } else if (type == "float") {
                rmTriggerAddScriptLine("int keyInt = (int)value;");
            } else {
                rmTriggerAddScriptLine("int keyInt = (int)value;");
            }
            rmTriggerAddScriptLine("int h = (keyInt ^ (keyInt >> 16)) * 73244539;");
            rmTriggerAddScriptLine("if(h < 0){");
                rmTriggerAddScriptLine("h = 0 - h;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return h % capacity;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int findSlot("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            rmTriggerAddScriptLine("int slot = hash(value);");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("if(!occupied[slot]){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("if(keys[slot] == value){");
                    rmTriggerAddScriptLine("return slot;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("slot = slot + 1;");
                rmTriggerAddScriptLine("if(slot >= capacity){");
                    rmTriggerAddScriptLine("slot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return -1;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void resize(){");
            rmTriggerAddScriptLine("int oldCapacity = capacity;");
            rmTriggerAddScriptLine("bool[] oldOccupied = occupied;");
            rmTriggerAddScriptLine(type+"[] oldKeys = keys;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("capacity = capacity * 2;");
            rmTriggerAddScriptLine("occupied = new bool(capacity, false);");
            rmTriggerAddScriptLine("keys = new "+type+"(capacity"+getArrayDefaultValue(type)+");");
            rmTriggerAddScriptLine("count = 0;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("for(int i = 0; i < oldCapacity; i++){");
                rmTriggerAddScriptLine("if(oldOccupied[i]){");
                    rmTriggerAddScriptLine("int slot = findSlot(oldKeys[i]);");
                    rmTriggerAddScriptLine("if(slot >= 0){");
                        rmTriggerAddScriptLine("occupied[slot] = true;");
                        rmTriggerAddScriptLine("keys[slot] = oldKeys[i];");
                        rmTriggerAddScriptLine("count++;");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool contains("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(value);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!occupied[slot]){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return keys[slot] == value;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool add("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("initialise();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(count * 10 >= capacity * 7){");
                rmTriggerAddScriptLine("resize();");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(value);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(occupied[slot]){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = true;");
            rmTriggerAddScriptLine("keys[slot] = value;");
            rmTriggerAddScriptLine("count++;");
            rmTriggerAddScriptLine("return true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("bool remove("+getParamQualifier(type)+" value"+getVariableDefaultValue(type)+"){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int slot = findSlot(value);");
            rmTriggerAddScriptLine("if(slot == -1){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(!occupied[slot]){");
                rmTriggerAddScriptLine("return false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("occupied[slot] = false;");
            rmTriggerAddScriptLine("count--;");
            rmTriggerAddScriptLine("");
            rmTriggerAddScriptLine("int nextSlot = slot + 1;");
            rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                rmTriggerAddScriptLine("nextSlot = 0;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("while(occupied[nextSlot]){");
                rmTriggerAddScriptLine(type+" rehashValue = keys[nextSlot];");
                rmTriggerAddScriptLine("occupied[nextSlot] = false;");
                rmTriggerAddScriptLine("count--;");
                rmTriggerAddScriptLine("int targetSlot = findSlot(rehashValue);");
                rmTriggerAddScriptLine("if(targetSlot >= 0){");
                    rmTriggerAddScriptLine("occupied[targetSlot] = true;");
                    rmTriggerAddScriptLine("keys[targetSlot] = rehashValue;");
                    rmTriggerAddScriptLine("count++;");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("nextSlot = nextSlot + 1;");
                rmTriggerAddScriptLine("if(nextSlot >= capacity){");
                    rmTriggerAddScriptLine("nextSlot = 0;");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return true;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("int size(){");
            rmTriggerAddScriptLine("return count;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("");
        rmTriggerAddScriptLine("void clear(){");
            rmTriggerAddScriptLine("if(!initialised){");
                rmTriggerAddScriptLine("return;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("for(int i = 0; i < capacity; i++){");
                rmTriggerAddScriptLine("occupied[i] = false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("count = 0;");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("};");
}