// Custom UI building

rmTriggerAddScriptLine("const string UI_SYSTEM_UNIT = \"Crate\";");
rmTriggerAddScriptLine("const string UI_SYSTEM_UNIT2 = \"CrateSmall\";");
rmTriggerAddScriptLine("const float UI_SYSTEM_SMALL_SCALE_MULTIPLIER = 1.355;");
rmTriggerAddScriptLine("const float UI_SYSTEM_LOOK_DISTANCE = 57.0;");
rmTriggerAddScriptLine("const float UI_SYSTEM_OFFSCREEN_Z = 1000.0;");
rmTriggerAddScriptLine("string(int, ref Parameters) EMPTY_DYNAMIC_UI_CONTENT = [](int pToUse = 1, ref Parameters parametersToUse) -> string { return \"\"; };");

rmTriggerAddScriptLine("class UiEntryParameterised {");
    rmTriggerAddScriptLine("Parameters parameters;");
    rmTriggerAddScriptLine("void(int, ref Parameters) handler = [](int p = 1, ref Parameters parametersToUse) -> void {};");
rmTriggerAddScriptLine("};");

rmTriggerAddScriptLine("class UiEntryStringParameterised {");
    rmTriggerAddScriptLine("Parameters parameters;");
    rmTriggerAddScriptLine("string(int, ref Parameters) getContent = EMPTY_DYNAMIC_UI_CONTENT;");
rmTriggerAddScriptLine("};");

createTypedPlayerSizingArray("int", "uiEntryOnTopOfArray");
createTypedPlayerSizingArray("float", "uiEntryXArray");
createTypedPlayerSizingArray("float", "uiEntryYArray");
createTypedPlayerSizingArray("float", "uiEntryWidthArray");
createTypedPlayerSizingArray("float", "uiEntryHeightArray");
createTypedPlayerSizingArray("string", "uiEntryContentArray");
createTypedPlayerSizingArray("string", "uiEntryRolloverNameArray");
createTypedPlayerSizingArray("string", "uiEntryRolloverDescriptionArray");
createTypedPlayerSizingArray("int", "uiEntryUnitArray");
createTypedPlayerSizingArray("int", "uiEntryUnitDataIndexArray");
createTypedPlayerSizingArray("int", "uiEntryRolloverDataIndexArray");
createTypedPlayerSizingArray("int", "uiEntryClickableDataIndexArray");
createTypedPlayerSizingArray("UiEntryParameterised", "uiEntryClickableHandlerArray");
createTypedPlayerSizingArray("int", "uiEntryUnitDataIndexInClickableArray");
createTypedPlayerSizingArray("int", "uiEntryOuterIndexInClickableArray");
createTypedPlayerSizingArray("int", "uiEntryDynamicDataIndexArray");
createTypedPlayerSizingArray("UiEntryStringParameterised", "uiEntryDynamicGetContentWrapperArray");
createTypedPlayerSizingArray("int", "uiEntryLastTimeArray");
createTypedPlayerSizingArray("int", "uiEntryFrequencyArray");
createTypedPlayerSizingArray("int", "uiEntryOuterIndexInDynamicArray");

rmTriggerAddScriptLine("bool uiSystemDebug = false;");
rmTriggerAddScriptLine("vector[] uiSystemLookAtArray = default;");
rmTriggerAddScriptLine("vector[] uiSystemLookAtForCameraArray = default;");
rmTriggerAddScriptLine("vector[] uiSystemCameraPositionArray = default;");
rmTriggerAddScriptLine("float[] uiSystemLookAtDistanceArray = default;");
rmTriggerAddScriptLine("float[] uiSystemLookAtHeadingArray = default;");
rmTriggerAddScriptLine("float[] uiSystemLookAtTiltArray = default;");
rmTriggerAddScriptLine("float[] uiSystemLookAtFovArray = default;");
rmTriggerAddScriptLine("vector[] uiSystemXAxisDirectionArray = default;");
rmTriggerAddScriptLine("vector[] uiSystemYAxisDirectionArray = default;");
rmTriggerAddScriptLine("bool[] uiSystemActiveArray = default;");
rmTriggerAddScriptLine("bool[] uiSystemDisableClickArray = default;");
rmTriggerAddScriptLine("bool[] uiSystemDeletableFlagsToRevertArray = default;");
rmTriggerAddScriptLine("bool[] uiSystemSelectableFlagsToRevertArray = default;");
rmTriggerAddScriptLine("int[] uiSystemAvailableIdArray = default;");
rmTriggerAddScriptLine("int uiSystemNextId = 0;");
rmTriggerAddScriptLine("int uiSystemCacheSize = 0;");
rmTriggerAddScriptLine("vector[] uiSystemPositionCacheArray = default;");
rmTriggerAddScriptLine("string[] uiSystemContentCacheArray = default;");
rmTriggerAddScriptLine("int[] uiSystemIdCacheArray = default;");
rmTriggerAddScriptLine("bool[] uiSystemCacheUsedArray = default;");
rmTriggerAddScriptLine("vector[] uiSystemPositionWorkingCacheArray = default;");
rmTriggerAddScriptLine("string[] uiSystemContentWorkingCacheArray = default;");
rmTriggerAddScriptLine("int[] uiSystemIdWorkingCacheArray = default;");
rmTriggerAddScriptLine("bool[] uiSystemIdWorkingCacheMissArray = default;");
rmTriggerAddScriptLine("int[] uiSystemRelicTechArray = default;");
rmTriggerAddScriptLine("int[] uiSystemClickedIndexArray = default;");
rmTriggerAddScriptLine("int[] uiSystemThrottleClickArray = default;");

rmTriggerAddScriptLine("void _uiSystemApplyCameraPosition(int p = 1){");
    rmTriggerAddScriptLine("if(trCurrentPlayer() == p){");
        rmTriggerAddScriptLine("cameraTrack.create(uiSystemLookAtForCameraArray[p], uiSystemLookAtDistanceArray[p], uiSystemLookAtHeadingArray[p], uiSystemLookAtTiltArray[p], uiSystemLookAtFovArray[p]);");
        rmTriggerAddScriptLine("cameraTrack.addWaypoint(1000000000, uiSystemLookAtForCameraArray[p], uiSystemLookAtDistanceArray[p], uiSystemLookAtHeadingArray[p], uiSystemLookAtTiltArray[p], uiSystemLookAtFovArray[p]);");
        rmTriggerAddScriptLine("cameraTrack.play();");
    rmTriggerAddScriptLine("}");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void setUiSystemCameraPosition(int p = 1, vector dest = cOriginVector, float distance = 0.0, float heading = 0.0, float tilt = 0.0, float fov = 40.0){");
    rmTriggerAddScriptLine("uiSystemLookAtForCameraArray[p] = dest;");
    rmTriggerAddScriptLine("uiSystemLookAtDistanceArray[p] = distance;");
    rmTriggerAddScriptLine("uiSystemLookAtHeadingArray[p] = heading;");
    rmTriggerAddScriptLine("uiSystemLookAtTiltArray[p] = tilt;");
    rmTriggerAddScriptLine("uiSystemLookAtFovArray[p] = fov;");
    rmTriggerAddScriptLine("float cameraH = degToRad(heading);");
    rmTriggerAddScriptLine("float cameraT = degToRad(tilt);");
    rmTriggerAddScriptLine("float cameraSinH = sin(cameraH);");
    rmTriggerAddScriptLine("float cameraCosH = cos(cameraH);");
    rmTriggerAddScriptLine("float cameraSinT = sin(cameraT);");
    rmTriggerAddScriptLine("float cameraCosT = cos(cameraT);");
    rmTriggerAddScriptLine("float cameraPosX = 0.0+dest.x-cameraCosH*cameraCosT*distance;");
    rmTriggerAddScriptLine("float cameraPosY = cameraSinT*distance+dest.y;");
    rmTriggerAddScriptLine("float cameraPosZ = 0.0+dest.z-cameraSinH*cameraCosT*distance;");
    rmTriggerAddScriptLine("uiSystemCameraPositionArray[p] = vector(cameraPosX, cameraPosY, cameraPosZ);");
    rmTriggerAddScriptLine("float canvasDistance = (tan(degToRad(0.5)) * UI_SYSTEM_LOOK_DISTANCE) / tan(degToRad(0.5 * fov));");
    rmTriggerAddScriptLine("float canvasDistanceFromLookPoint = -canvasDistance + distance;");
    rmTriggerAddScriptLine("float canvasPosX = 0.0+dest.x-cameraCosH*cameraCosT*canvasDistanceFromLookPoint;");
    rmTriggerAddScriptLine("float canvasPosY = cameraSinT*canvasDistanceFromLookPoint+dest.y;");
    rmTriggerAddScriptLine("float canvasPosZ = 0.0+dest.z-cameraSinH*cameraCosT*canvasDistanceFromLookPoint;");
    rmTriggerAddScriptLine("uiSystemLookAtArray[p] = vector(canvasPosX, canvasPosY, canvasPosZ);");
    rmTriggerAddScriptLine("uiSystemXAxisDirectionArray[p] = vector(cameraSinH, 0.0, -cameraCosH);");
    rmTriggerAddScriptLine("uiSystemYAxisDirectionArray[p] = vector(cameraSinT * cameraCosH, cameraCosT, cameraSinT * cameraSinH);");
    rmTriggerAddScriptLine("if(uiSystemActiveArray[p]){");
        rmTriggerAddScriptLine("_uiSystemApplyCameraPosition(p);");
    rmTriggerAddScriptLine("}");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void enterUiSystem(int p = 1, bool disableClick = false){");
    rmTriggerAddScriptLine("uiSystemDisableClickArray[p] = disableClick;");
    rmTriggerAddScriptLine("if(uiSystemActiveArray[p] == false){");
        rmTriggerAddScriptLine("uiSystemActiveArray[p] = true;");
        rmTriggerAddScriptLine("int deleteableOffset = p * cNumberProtoUnits;");
        rmTriggerAddScriptLine("for(int i = 0; i < cNumberProtoUnits; i++){");
            rmTriggerAddScriptLine("bool deleteable = kbPlayerGetProtoStatFlag(p, i, cProtoUnitFlagDeleteable);");
            rmTriggerAddScriptLine("uiSystemDeletableFlagsToRevertArray[deleteableOffset + i] = deleteable;");
            rmTriggerAddScriptLine("if(deleteable){");
                rmTriggerAddScriptLine("trProtoUnitSetFlag(p, kbProtoUnitGetName(i), \"Deleteable\", false);");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("if(trCurrentPlayer() == p){");
            rmTriggerAddScriptLine("int offset = 0;");
            rmTriggerAddScriptLine("for(int q = 0; q <= cNumberPlayers; q++){");
                rmTriggerAddScriptLine("for(int i = 0; i < cNumberProtoUnits; i++){");
                    rmTriggerAddScriptLine("bool selectable = kbPlayerGetProtoStatFlag(q, i, cProtoUnitFlagSelectable);");
                    rmTriggerAddScriptLine("uiSystemSelectableFlagsToRevertArray[i + offset] = selectable;");
                    rmTriggerAddScriptLine("if(selectable){");
                        rmTriggerAddScriptLine("trProtoUnitSetFlag(q, kbProtoUnitGetName(i), \"Selectable\", false);");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("offset = offset + cNumberProtoUnits;");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("trProtoUnitSetFlag(p, UI_SYSTEM_UNIT, \"Deleteable\", true);");
        rmTriggerAddScriptLine("trProtoUnitSetFlag(p, UI_SYSTEM_UNIT2, \"Deleteable\", true);");
        rmTriggerAddScriptLine("trProtoUnitSetFlag(p, UI_SYSTEM_UNIT, \"Selectable\", true);");
        rmTriggerAddScriptLine("trProtoUnitSetFlag(p, UI_SYSTEM_UNIT2, \"Selectable\", true);");
        rmTriggerAddScriptLine("vector lookAt = uiSystemLookAtArray[p];");
        rmTriggerAddScriptLine("int tempToSelect = trUnitCreateForced(UI_SYSTEM_UNIT, lookAt.x, lookAt.y, lookAt.z, 0, p);");
        rmTriggerAddScriptLine("selectSingle(tempToSelect);");
        rmTriggerAddScriptLine("if (trCurrentPlayer() == p){");
            rmTriggerAddScriptLine("trUnitGameSelect(true);");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("trUnitDestroy();");
        rmTriggerAddScriptLine("_uiSystemApplyCameraPosition(p);");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("int unitCount = uiEntryUnitArraySize(p);");
    rmTriggerAddScriptLine("for(int i = 0; i < unitCount; i++){");
        rmTriggerAddScriptLine("selectSingle(uiEntryUnitArrayGet(p, i));");
        rmTriggerAddScriptLine("trUnitDestroy();");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("uiEntryOnTopOfArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryXArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryYArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryWidthArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryHeightArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryContentArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryRolloverNameArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryRolloverDescriptionArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryUnitArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryUnitDataIndexArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryRolloverDataIndexArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryClickableDataIndexArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryClickableHandlerArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryUnitDataIndexInClickableArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryOuterIndexInClickableArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryDynamicDataIndexArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryDynamicGetContentWrapperArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryLastTimeArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryFrequencyArrayClear(p);");
    rmTriggerAddScriptLine("uiEntryOuterIndexInDynamicArrayClear(p);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int _uiSystemGetAvailableId(){");
    rmTriggerAddScriptLine("int size = uiSystemAvailableIdArray.size();");
    rmTriggerAddScriptLine("if(size > 0){");
        rmTriggerAddScriptLine("int id = uiSystemAvailableIdArray[size - 1];");
        rmTriggerAddScriptLine("uiSystemAvailableIdArray.removeIndex(size - 1);");
        rmTriggerAddScriptLine("return id;");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("int id = uiSystemNextId;");
    rmTriggerAddScriptLine("uiSystemNextId++;");
    rmTriggerAddScriptLine("return id;");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void postEnterUiSystem(int p = 1, int swapOutTime = 1){");
    rmTriggerAddScriptLine("Parameters parameters = createParameters();");
    rmTriggerAddScriptLine("parameters.ints.add(p);");
    rmTriggerAddScriptLine("if(p == trCurrentPlayer()){");
        rmTriggerAddScriptLine("int count = uiEntryXArraySize(p);");
        rmTriggerAddScriptLine("if(count > uiSystemPositionWorkingCacheArray.size()){");
            rmTriggerAddScriptLine("uiSystemPositionWorkingCacheArray.resize(count, cOriginVector);");
            rmTriggerAddScriptLine("uiSystemContentWorkingCacheArray.resize(count, \"\");");
            rmTriggerAddScriptLine("uiSystemIdWorkingCacheArray.resize(count, -1);");
            rmTriggerAddScriptLine("uiSystemIdWorkingCacheMissArray.resize(count, false);");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("for(int i = 0; i < count; i++){");
            rmTriggerAddScriptLine("vector promptLocation = uiSystemLookAtArray[p] + uiSystemXAxisDirectionArray[p] * uiEntryXArrayGet(p, i) + uiSystemYAxisDirectionArray[p] * uiEntryYArrayGet(p, i);");
            rmTriggerAddScriptLine("vector directionVector = xsVectorNormalize(promptLocation - uiSystemCameraPositionArray[p]);");
            rmTriggerAddScriptLine("vector finalLocation = uiSystemLookAtArray[p] + directionVector * 100000000.0;");
            rmTriggerAddScriptLine("string content = uiEntryContentArrayGet(p, i);");
            rmTriggerAddScriptLine("int id = -1;");
            rmTriggerAddScriptLine("int onTopOfId = uiEntryOnTopOfArrayGet(p, i);");
            rmTriggerAddScriptLine("if(onTopOfId < 0 || uiSystemIdWorkingCacheMissArray[onTopOfId] == false){");
                rmTriggerAddScriptLine("for(int j = 0; j < uiSystemCacheSize; j++){");
                    rmTriggerAddScriptLine("if(uiSystemCacheUsedArray[j] == false && uiSystemPositionCacheArray[j] == finalLocation && uiSystemContentCacheArray[j] == content){");
                        rmTriggerAddScriptLine("uiSystemCacheUsedArray[j] = true;");
                        rmTriggerAddScriptLine("id = uiSystemIdCacheArray[j];");
                        rmTriggerAddScriptLine("break;");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(id < 0){");
                rmTriggerAddScriptLine("id = _uiSystemGetAvailableId();");
                rmTriggerAddScriptLine("if(content != \"\"){");
                    rmTriggerAddScriptLine("trWorldSpacePromptArea(\"UiSystem\" + id, finalLocation, \"<icon=(1,10000)(0)>\n\" + content, cOriginVector, false);");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("uiSystemIdWorkingCacheMissArray[i] = true;");
            rmTriggerAddScriptLine("} else {");
                rmTriggerAddScriptLine("uiSystemIdWorkingCacheMissArray[i] = false;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("uiSystemPositionWorkingCacheArray[i] = finalLocation;");
            rmTriggerAddScriptLine("uiSystemContentWorkingCacheArray[i] = content;");
            rmTriggerAddScriptLine("uiSystemIdWorkingCacheArray[i] = id;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("for(int i = uiSystemCacheSize - 1; i >= 0; i--){");
            rmTriggerAddScriptLine("if(uiSystemCacheUsedArray[i] == false){");
                rmTriggerAddScriptLine("if(swapOutTime > 0){");
                    rmTriggerAddScriptLine("parameters.ints.add(uiSystemIdCacheArray[i]);");
                rmTriggerAddScriptLine("} else {");
                    rmTriggerAddScriptLine("int id = uiSystemIdCacheArray[i];");
                    rmTriggerAddScriptLine("trWorldSpacePromptHide(\"UiSystem\" + id);");
                    rmTriggerAddScriptLine("uiSystemAvailableIdArray.add(id);");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("if(count > uiSystemPositionCacheArray.size()){");
            rmTriggerAddScriptLine("uiSystemPositionCacheArray.resize(count, cOriginVector);");
            rmTriggerAddScriptLine("uiSystemContentCacheArray.resize(count, \"\");");
            rmTriggerAddScriptLine("uiSystemIdCacheArray.resize(count, -1);");
            rmTriggerAddScriptLine("uiSystemCacheUsedArray.resize(count, false);");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("uiSystemCacheSize = count;");
        rmTriggerAddScriptLine("for(int i = 0; i < count; i++){");
            rmTriggerAddScriptLine("uiSystemPositionCacheArray[i] = uiSystemPositionWorkingCacheArray[i];");
            rmTriggerAddScriptLine("uiSystemContentCacheArray[i] = uiSystemContentWorkingCacheArray[i];");
            rmTriggerAddScriptLine("uiSystemIdCacheArray[i] = uiSystemIdWorkingCacheArray[i];");
            rmTriggerAddScriptLine("uiSystemCacheUsedArray[i] = false;");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("if(swapOutTime > 0){");
        rmTriggerAddScriptLine("schedulerWithParameters.add(swapOutTime, parameters, [](int iteration = 1, ref Parameters parameters) -> bool {");
            rmTriggerAddScriptLine("if(parameters.ints[0] == trCurrentPlayer()){");
                rmTriggerAddScriptLine("int intParamCount = parameters.ints.size();");
                rmTriggerAddScriptLine("for(int i = 1; i < intParamCount; i++){");
                    rmTriggerAddScriptLine("int id = parameters.ints[i];");
                    rmTriggerAddScriptLine("trWorldSpacePromptHide(\"UiSystem\" + id);");
                    rmTriggerAddScriptLine("uiSystemAvailableIdArray.add(id);");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("return false;");
        rmTriggerAddScriptLine("});");
    rmTriggerAddScriptLine("}");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void exitUiSystem(int p = 1, bool normaliseCamera = false, float fov = 40.0){");
    rmTriggerAddScriptLine("if(uiSystemActiveArray[p]){");
        rmTriggerAddScriptLine("uiSystemActiveArray[p] = false;");
        rmTriggerAddScriptLine("vector lookAt = uiSystemLookAtArray[p];");
        rmTriggerAddScriptLine("int tempToSelect = trUnitCreateForced(UI_SYSTEM_UNIT, lookAt.x, lookAt.y, lookAt.z, 0, p);");
        rmTriggerAddScriptLine("selectSingle(tempToSelect);");
        rmTriggerAddScriptLine("if (trCurrentPlayer() == p){");
            rmTriggerAddScriptLine("trUnitGameSelect(true);");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("trUnitDestroy();");
        rmTriggerAddScriptLine("int deleteableOffset = p * cNumberProtoUnits;");
        rmTriggerAddScriptLine("for(int i = 0; i < cNumberProtoUnits; i++){");
            rmTriggerAddScriptLine("bool deleteable = uiSystemDeletableFlagsToRevertArray[deleteableOffset + i];");
            rmTriggerAddScriptLine("if(deleteable){");
                rmTriggerAddScriptLine("trProtoUnitSetFlag(p, kbProtoUnitGetName(i), \"Deleteable\", true);");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("if(trCurrentPlayer() == p){");
            rmTriggerAddScriptLine("int offset = 0;");
            rmTriggerAddScriptLine("for(int q = 0; q <= cNumberPlayers; q++){");
                rmTriggerAddScriptLine("for(int i = 0; i < cNumberProtoUnits; i++){");
                    rmTriggerAddScriptLine("bool selectable = uiSystemSelectableFlagsToRevertArray[i + offset];");
                    rmTriggerAddScriptLine("if(selectable){");
                        rmTriggerAddScriptLine("trProtoUnitSetFlag(q, kbProtoUnitGetName(i), \"Selectable\", true);");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("offset = offset + cNumberProtoUnits;");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("if(trCurrentPlayer() == p){");
            rmTriggerAddScriptLine("if(normaliseCamera){");
                rmTriggerAddScriptLine("cameraTrack.create(uiSystemLookAtForCameraArray[p], uiSystemLookAtDistanceArray[p], uiSystemLookAtHeadingArray[p], uiSystemLookAtTiltArray[p], uiSystemLookAtFovArray[p]);");
                rmTriggerAddScriptLine("cameraTrack.addWaypoint(1, uiSystemLookAtForCameraArray[p], uiSystemLookAtDistanceArray[p], uiSystemLookAtHeadingArray[p], uiSystemLookAtTiltArray[p], uiSystemLookAtFovArray[p]);");
                rmTriggerAddScriptLine("cameraTrack.play(true, 0);");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("for(int i = uiSystemCacheSize - 1; i >= 0; i--){");
                rmTriggerAddScriptLine("int id = uiSystemIdCacheArray[i];");
                rmTriggerAddScriptLine("trWorldSpacePromptHide(\"UiSystem\" + id);");
                rmTriggerAddScriptLine("uiSystemAvailableIdArray.add(id);");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("uiSystemCacheSize = 0;");
        rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("int unitCount = uiEntryUnitArraySize(p);");
        rmTriggerAddScriptLine("for(int i = 0; i < unitCount; i++){");
            rmTriggerAddScriptLine("selectSingle(uiEntryUnitArrayGet(p, i));");
            rmTriggerAddScriptLine("trUnitDestroy();");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("}");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemRefreshUiUnit(int p = 1, int index = 0){");
    rmTriggerAddScriptLine("int unitDataIndex = uiEntryUnitDataIndexArrayGet(p, index);");
    rmTriggerAddScriptLine("int rolloverDataIndex = uiEntryRolloverDataIndexArrayGet(p, index);");
    rmTriggerAddScriptLine("int clickableDataIndex = uiEntryClickableDataIndexArrayGet(p, index);");
    rmTriggerAddScriptLine("selectSingle(uiEntryUnitArrayGet(p, unitDataIndex));");
    rmTriggerAddScriptLine("trUnitDestroy();");
    
    rmTriggerAddScriptLine("bool hoverable = rolloverDataIndex >= 0;");
    rmTriggerAddScriptLine("string unitType = hoverable ? UI_SYSTEM_UNIT2 : UI_SYSTEM_UNIT;");
    rmTriggerAddScriptLine("vector lookAt = uiSystemLookAtArray[p];");
    rmTriggerAddScriptLine("float width = uiEntryWidthArrayGet(p, unitDataIndex);");
    rmTriggerAddScriptLine("float height = uiEntryHeightArrayGet(p, unitDataIndex);");
    rmTriggerAddScriptLine("vector pos = lookAt + uiSystemXAxisDirectionArray[p] * uiEntryXArrayGet(p, index) + uiSystemYAxisDirectionArray[p] * (uiEntryYArrayGet(p, index) + height / 2.0);");
    rmTriggerAddScriptLine("int unit = trUnitCreateForced(unitType, pos.x, pos.y, pos.z, 0, p);");
    rmTriggerAddScriptLine("selectSingle(unit);");
    rmTriggerAddScriptLine("if(!uiSystemDebug){");
        rmTriggerAddScriptLine("trUnitChangeProtoUnit(unitType, false, true);");
        rmTriggerAddScriptLine("trUnitSetShading(cShaderBurning, 1000.0);");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("if(hoverable){");
        rmTriggerAddScriptLine("trUnitSetScale(UI_SYSTEM_SMALL_SCALE_MULTIPLIER * height, 0.004, UI_SYSTEM_SMALL_SCALE_MULTIPLIER * width);");
    rmTriggerAddScriptLine("} else {");
        rmTriggerAddScriptLine("trUnitSetScale(height, 0.004, width);");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("trUnitRotateZ(uiSystemLookAtTiltArray[p] - 90, true);");
    rmTriggerAddScriptLine("trUnitRotateY(-uiSystemLookAtHeadingArray[p] - 180, true);");
    rmTriggerAddScriptLine("if(clickableDataIndex < 0 || uiSystemDisableClickArray[p]){");
        rmTriggerAddScriptLine("trUnitSetFlag(cUnitFlagIsUnbuilding, true);");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("if(hoverable){");
        rmTriggerAddScriptLine("trRelicForce(unit, kbTechGetName(uiSystemRelicTechArray[rolloverDataIndex]));");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("uiEntryUnitArraySet(p, unitDataIndex, unit);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemRefreshUiTech(int p = 1, int index = 0){");
    rmTriggerAddScriptLine("int rolloverDataIndex = uiEntryRolloverDataIndexArrayGet(p, index);");
    rmTriggerAddScriptLine("int relicTech = uiSystemRelicTechArray[rolloverDataIndex];");
    rmTriggerAddScriptLine("trTechHideEffects(relicTech, p, true);");
    rmTriggerAddScriptLine("trTechSetStringID(relicTech, p, uiEntryRolloverNameArrayGet(p, rolloverDataIndex) + \"<color=0,0,0>\", cXSTechEffectDisplayName);");
    rmTriggerAddScriptLine("trTechSetStringID(relicTech, p, \"</color>\n\" + uiEntryRolloverDescriptionArrayGet(p, rolloverDataIndex), cXSTechEffectRollover);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemAddDisplay(int p = 1, float x = 0.0, float y = 0.0, string content = \"\", int onTopOf = -1){");
    rmTriggerAddScriptLine("uiEntryOnTopOfArrayAdd(p, onTopOf);");
    rmTriggerAddScriptLine("uiEntryXArrayAdd(p, x);");
    rmTriggerAddScriptLine("uiEntryYArrayAdd(p, y);");
    rmTriggerAddScriptLine("uiEntryContentArrayAdd(p, content);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemAddUnit(int p = 1, float width = 0.0, float height = 0.0){");
    rmTriggerAddScriptLine("uiEntryUnitDataIndexArrayAdd(p, uiEntryUnitArraySize(p));");
    rmTriggerAddScriptLine("uiEntryWidthArrayAdd(p, width);");
    rmTriggerAddScriptLine("uiEntryHeightArrayAdd(p, height);");
    rmTriggerAddScriptLine("uiEntryUnitArrayAdd(p, -1);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemAddRollover(int p = 1, string rolloverName = \"\", string rolloverDescription = \"\"){");
    rmTriggerAddScriptLine("uiEntryRolloverDataIndexArrayAdd(p, uiEntryRolloverNameArraySize(p));");
    rmTriggerAddScriptLine("uiEntryRolloverNameArrayAdd(p, rolloverName);");
    rmTriggerAddScriptLine("uiEntryRolloverDescriptionArrayAdd(p, rolloverDescription);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemAddClickable(int p = 1, ref Parameters parameters, void(int, ref Parameters) handler = [](int pToUse = 1, ref Parameters parametersToUse) -> void {}){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryClickableDataIndexArrayAdd(p, uiEntryClickableHandlerArraySize(p));");
    rmTriggerAddScriptLine("UiEntryParameterised wrapperHandler;");
    rmTriggerAddScriptLine("wrapperHandler.parameters = parameters;");
    rmTriggerAddScriptLine("wrapperHandler.handler = handler;");
    rmTriggerAddScriptLine("uiEntryClickableHandlerArrayAdd(p, wrapperHandler);");
    rmTriggerAddScriptLine("int unitDataIndex = uiEntryUnitDataIndexArrayGet(p, outerIndex);");
    rmTriggerAddScriptLine("uiEntryUnitDataIndexInClickableArrayAdd(p, unitDataIndex);");
    rmTriggerAddScriptLine("uiEntryOuterIndexInClickableArrayAdd(p, outerIndex);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _uiSystemAddDynamic(int p = 1, int frequency = 0, string(int, ref Parameters) getContent = EMPTY_DYNAMIC_UI_CONTENT, ref Parameters parameters){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryDynamicDataIndexArrayAdd(p, uiEntryFrequencyArraySize(p));");
    rmTriggerAddScriptLine("UiEntryStringParameterised getDisplayWrapper;");
    rmTriggerAddScriptLine("getDisplayWrapper.parameters = parameters;");
    rmTriggerAddScriptLine("getDisplayWrapper.getContent = getContent;");
    rmTriggerAddScriptLine("uiEntryDynamicGetContentWrapperArrayAdd(p, getDisplayWrapper);");
    rmTriggerAddScriptLine("uiEntryLastTimeArrayAdd(p, xsGetTimeMS());");
    rmTriggerAddScriptLine("uiEntryFrequencyArrayAdd(p, frequency);");
    rmTriggerAddScriptLine("uiEntryOuterIndexInDynamicArrayAdd(p, outerIndex);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int uiSystemAddDisplay(int p = 1, float x = 0.0, float y = 0.0, string content = \"\", int onTopOf = -1){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryXArraySize(p);");
    rmTriggerAddScriptLine("_uiSystemAddDisplay(p, x, y, content, onTopOf);");
    
    rmTriggerAddScriptLine("uiEntryUnitDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("uiEntryRolloverDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("uiEntryClickableDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("uiEntryDynamicDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("return outerIndex;");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int uiSystemAddDisplayWithHover(int p = 1, float x = 0.0, float y = 0.0, float width = 0.0, float height = 0.0, string content = \"\", string rolloverName = \"\", string rolloverDescription = \"\", int onTopOf = -1){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryXArraySize(p);");
    rmTriggerAddScriptLine("_uiSystemAddDisplay(p, x, y, content, onTopOf);");
    
    rmTriggerAddScriptLine("_uiSystemAddUnit(p, width, height);");
    rmTriggerAddScriptLine("_uiSystemAddRollover(p, rolloverName, rolloverDescription);");
    rmTriggerAddScriptLine("uiEntryClickableDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("uiEntryDynamicDataIndexArrayAdd(p, -1);");
    
    rmTriggerAddScriptLine("_uiSystemRefreshUiTech(p, outerIndex);");
    rmTriggerAddScriptLine("_uiSystemRefreshUiUnit(p, outerIndex);");
    rmTriggerAddScriptLine("return outerIndex;");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int uiSystemAddClickable(int p = 1, float x = 0.0, float y = 0.0, float width = 0.0, float height = 0.0, string content = \"\", ");
        rmTriggerAddScriptLine("ref Parameters parameters, void(int, ref Parameters) handler = [](int pToUse = 1, ref Parameters parametersToUse) -> void {}, int onTopOf = -1){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryXArraySize(p);");
    rmTriggerAddScriptLine("_uiSystemAddDisplay(p, x, y, content, onTopOf);");
    
    rmTriggerAddScriptLine("_uiSystemAddUnit(p, width, height);");
    rmTriggerAddScriptLine("uiEntryRolloverDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("_uiSystemAddClickable(p, parameters, handler);");
    rmTriggerAddScriptLine("uiEntryDynamicDataIndexArrayAdd(p, -1);");
    
    rmTriggerAddScriptLine("_uiSystemRefreshUiUnit(p, outerIndex);");
    rmTriggerAddScriptLine("return outerIndex;");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int uiSystemAddClickableWithHover(int p = 1, float x = 0.0, float y = 0.0, float width = 0.0, float height = 0.0, string content = \"\", string rolloverName = \"\", string rolloverDescription = \"\", ");
        rmTriggerAddScriptLine("ref Parameters parameters, void(int, ref Parameters) handler = [](int pToUse = 1, ref Parameters parametersToUse) -> void {}, int onTopOf = -1){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryXArraySize(p);");
    rmTriggerAddScriptLine("_uiSystemAddDisplay(p, x, y, content, onTopOf);");
    
    rmTriggerAddScriptLine("_uiSystemAddUnit(p, width, height);");
    rmTriggerAddScriptLine("_uiSystemAddRollover(p, rolloverName, rolloverDescription);");
    rmTriggerAddScriptLine("_uiSystemAddClickable(p, parameters, handler);");
    rmTriggerAddScriptLine("uiEntryDynamicDataIndexArrayAdd(p, -1);");
    
    rmTriggerAddScriptLine("_uiSystemRefreshUiTech(p, outerIndex);");
    rmTriggerAddScriptLine("_uiSystemRefreshUiUnit(p, outerIndex);");
    rmTriggerAddScriptLine("return outerIndex;");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int uiSystemAddDisplayDynamic(int p = 1, float x = 0.0, float y = 0.0, int frequency = 0, string(int, ref Parameters) getContent = EMPTY_DYNAMIC_UI_CONTENT, ref Parameters parameters, int onTopOf = -1){");
    rmTriggerAddScriptLine("int outerIndex = uiEntryXArraySize(p);");
    rmTriggerAddScriptLine("string content = (p == trCurrentPlayer()) ? getContent(p, parameters) : \"\";");
    rmTriggerAddScriptLine("_uiSystemAddDisplay(p, x, y, content, onTopOf);");
    
    rmTriggerAddScriptLine("uiEntryUnitDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("uiEntryRolloverDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("uiEntryClickableDataIndexArrayAdd(p, -1);");
    rmTriggerAddScriptLine("_uiSystemAddDynamic(p, frequency, getContent, parameters);");
    rmTriggerAddScriptLine("return outerIndex;");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void _processUiSystems(){");
    rmTriggerAddScriptLine("int currentTime = xsGetTimeMS();");
    rmTriggerAddScriptLine("for(int p = 1; p <= "+cNumberPlayers+"; p++){");
        rmTriggerAddScriptLine("uiSystemClickedIndexArray[p] = -1;");
        rmTriggerAddScriptLine("if(uiSystemActiveArray[p]){");
            rmTriggerAddScriptLine("int dynamicCount = uiEntryLastTimeArraySize(p);");
            rmTriggerAddScriptLine("for(int i = 0; i < dynamicCount; i++){");
                rmTriggerAddScriptLine("int frequency = uiEntryFrequencyArrayGet(p, i);");
                rmTriggerAddScriptLine("int lastTime = uiEntryLastTimeArrayGet(p, i);");
                rmTriggerAddScriptLine("if(currentTime - frequency >= lastTime){");
                    rmTriggerAddScriptLine("uiEntryLastTimeArraySet(p, i, currentTime);");
                    rmTriggerAddScriptLine("if(p == trCurrentPlayer()){");
                        rmTriggerAddScriptLine("UiEntryStringParameterised getContentWrapper = uiEntryDynamicGetContentWrapperArrayGet(p, i);");
                        rmTriggerAddScriptLine("Parameters parameters = getContentWrapper.parameters;");
                        rmTriggerAddScriptLine("string(int, ref Parameters) getContent = getContentWrapper.getContent;");
                        rmTriggerAddScriptLine("string newContent = getContent(p, parameters);");
                        rmTriggerAddScriptLine("int outerIndex = uiEntryOuterIndexInDynamicArrayGet(p, i);");
                        rmTriggerAddScriptLine("if(newContent != uiEntryContentArrayGet(p, outerIndex)){");
                            rmTriggerAddScriptLine("uiEntryContentArraySet(p, outerIndex, newContent);");
                            rmTriggerAddScriptLine("uiSystemContentCacheArray[outerIndex] = newContent;");
                            rmTriggerAddScriptLine("if(newContent != \"\"){");
                                rmTriggerAddScriptLine("trWorldSpacePromptArea(\"UiSystem\" + uiSystemIdCacheArray[outerIndex], uiSystemPositionWorkingCacheArray[outerIndex], ");
                                        rmTriggerAddScriptLine("\"<icon=(1,10000)(0)>\n\" + newContent, cOriginVector, false);");
                            rmTriggerAddScriptLine("} else {");
                                rmTriggerAddScriptLine("trWorldSpacePromptHide(\"UiSystem\" + uiSystemIdCacheArray[outerIndex]);");
                            rmTriggerAddScriptLine("}");
                        rmTriggerAddScriptLine("}");
                    rmTriggerAddScriptLine("}");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("int clickedEntryIndex = -1;");
            rmTriggerAddScriptLine("bool validClick = true;");
            rmTriggerAddScriptLine("int count = uiEntryUnitDataIndexInClickableArraySize(p);");
            rmTriggerAddScriptLine("for(int i = 0; i < count; i++){");
                rmTriggerAddScriptLine("int unitDataIndex = uiEntryUnitDataIndexInClickableArrayGet(p, i);");
                rmTriggerAddScriptLine("int unitId = uiEntryUnitArrayGet(p, unitDataIndex);");
                rmTriggerAddScriptLine("selectSingle(unitId);");
                rmTriggerAddScriptLine("if(trUnitAlive() == false){");
                    rmTriggerAddScriptLine("uiSystemThrottleClickArray[p] = 0;");
                    rmTriggerAddScriptLine("if(clickedEntryIndex == -1){");
                        rmTriggerAddScriptLine("clickedEntryIndex = i;");
                    rmTriggerAddScriptLine("} else {");
                        rmTriggerAddScriptLine("validClick = false;");
                    rmTriggerAddScriptLine("}");
                    rmTriggerAddScriptLine("_uiSystemRefreshUiUnit(p, uiEntryOuterIndexInClickableArrayGet(p, i));");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(validClick && clickedEntryIndex >= 0){");
                rmTriggerAddScriptLine("uiSystemClickedIndexArray[p] = clickedEntryIndex;");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("if(trCurrentPlayer() == p && (trUnitTypeIsSelected(UI_SYSTEM_UNIT, true) || trUnitTypeIsSelected(UI_SYSTEM_UNIT2, true))){");
                rmTriggerAddScriptLine("if(xsGetTimeMS() >= uiSystemThrottleClickArray[p]){");
                    rmTriggerAddScriptLine("uiSystemThrottleClickArray[p] = xsGetTimeMS() + 500;");
                    rmTriggerAddScriptLine("trExecuteConsoleCommand(\"uiDeleteSelectedUnit(true)\");");
                rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("}");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("for(int p = 1; p <= "+cNumberPlayers+"; p++){");
        rmTriggerAddScriptLine("int index = uiSystemClickedIndexArray[p];");
        rmTriggerAddScriptLine("if(index >= 0){");
            rmTriggerAddScriptLine("UiEntryParameterised wrapperHandler = uiEntryClickableHandlerArrayGet(p, index);");
            rmTriggerAddScriptLine("Parameters parameters = wrapperHandler.parameters;");
            rmTriggerAddScriptLine("void(int, ref Parameters) handler = wrapperHandler.handler;");
            rmTriggerAddScriptLine("handler(p, parameters);");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("}");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("void initialiseUiSystems(bool debug = false){");
    rmTriggerAddScriptLine("uiSystemDebug = debug;");
    rmTriggerAddScriptLine("uiSystemLookAtArray.resize("+(cNumberPlayers+1)+", cOriginVector);");
    rmTriggerAddScriptLine("uiSystemLookAtForCameraArray.resize("+(cNumberPlayers+1)+", cOriginVector);");
    rmTriggerAddScriptLine("uiSystemCameraPositionArray.resize("+(cNumberPlayers+1)+", cOriginVector);");
    rmTriggerAddScriptLine("uiSystemLookAtDistanceArray.resize("+(cNumberPlayers+1)+", UI_SYSTEM_LOOK_DISTANCE);");
    rmTriggerAddScriptLine("uiSystemLookAtHeadingArray.resize("+(cNumberPlayers+1)+", 90.0);");
    rmTriggerAddScriptLine("uiSystemLookAtTiltArray.resize("+(cNumberPlayers+1)+", 90.0);");
    rmTriggerAddScriptLine("uiSystemLookAtFovArray.resize("+(cNumberPlayers+1)+", 40.0);");
    rmTriggerAddScriptLine("uiSystemXAxisDirectionArray.resize("+(cNumberPlayers+1)+", vector(1.0, 0.0, 0.0));");
    rmTriggerAddScriptLine("uiSystemYAxisDirectionArray.resize("+(cNumberPlayers+1)+", vector(0.0, 0.0, 1.0));");
    rmTriggerAddScriptLine("uiSystemActiveArray.resize("+(cNumberPlayers+1)+", false);");
    rmTriggerAddScriptLine("uiSystemDisableClickArray.resize("+(cNumberPlayers+1)+", false);");
    rmTriggerAddScriptLine("uiSystemDeletableFlagsToRevertArray.resize("+(cNumberPlayers+1)+" * cNumberProtoUnits, false);");
    rmTriggerAddScriptLine("uiSystemSelectableFlagsToRevertArray.resize("+(cNumberPlayers+1)+" * cNumberProtoUnits, false);");
    rmTriggerAddScriptLine("uiSystemClickedIndexArray.resize("+(cNumberPlayers+1)+", -1);");
    rmTriggerAddScriptLine("uiSystemThrottleClickArray.resize("+(cNumberPlayers+1)+", 0);");
    rmTriggerAddScriptLine("for(int p = 1; p <= "+cNumberPlayers+"; p++){");
        rmTriggerAddScriptLine("setUiSystemCameraPosition(p, vector(0.5 * kbGetMapXSize(), -10100.0, 0.5 * kbGetMapZSize()), 100.0, 45.0, 89.0, 40.0);");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("for(int i = 0; i < cNumberTechs; i++){");
        rmTriggerAddScriptLine("string tech = kbTechGetName(i);");
        rmTriggerAddScriptLine("if(xsStringStartsWith(tech, \"Relic\", true) && xsStringEndsWith(tech, \"Respawn\", true) == false){");
            rmTriggerAddScriptLine("uiSystemRelicTechArray.add(i);");
        rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("string[] systemUnits = string2Array(UI_SYSTEM_UNIT, UI_SYSTEM_UNIT2);");
    rmTriggerAddScriptLine("for(int p = 1; p <= "+cNumberPlayers+"; p++){");
        forEachStart("string", "systemUnit", "systemUnits");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"Collideable\", false);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"ForceDeleteable\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"Invulnerable\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"InvulnerableToAreaDamage\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"DontMarkExtraFog\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"VisibleUnderFog\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"ForceToNature\", false);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"TieToGround\", false);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"Selectable\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"Deleteable\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"FadeInOnBuild\", !debug);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"HasLOS\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"ObscuredByUnits\", true);");
            rmTriggerAddScriptLine("trProtoUnitSetUnitType(p, systemUnit, \"Building\", true);");
            rmTriggerAddScriptLine("if(p != trCurrentPlayer()){");
                rmTriggerAddScriptLine("trProtoUnitSetFlag(p, systemUnit, \"OnlyInEditor\", true);");
            rmTriggerAddScriptLine("}");
            rmTriggerAddScriptLine("trModifyProtounitData(systemUnit, p, cXSProtoEffectBuildPoints, 100000, cXSRelativityAssign);");
            rmTriggerAddScriptLine("trModifyProtounitData(systemUnit, p, cXSProtoEffectLOS, debug ? 5.0 : 0.0, cXSRelativityAssign);");
        forEachEnd();
        rmTriggerAddScriptLine("trProtoUnitSetFlag(p, UI_SYSTEM_UNIT2, \"Relic\", true);");
    rmTriggerAddScriptLine("}");
    rmTriggerAddScriptLine("scheduler.add(1, [](int iteration = 0) -> bool {");
        rmTriggerAddScriptLine("_processUiSystems();");
        rmTriggerAddScriptLine("return true;");
    rmTriggerAddScriptLine("});");
rmTriggerAddScriptLine("}");

// UI helper methods

rmTriggerAddScriptLine("string displayCompensatedIcon(int width = 1, int height = 1, string icon = \"0\"){");
    rmTriggerAddScriptLine("float compensationValue = playerScreenIconSizeCompensationValue[trCurrentPlayer()];");
    rmTriggerAddScriptLine("int correctedWidth = round(compensationValue * width);");
    rmTriggerAddScriptLine("int correctedHeight = round(compensationValue * height);");
    rmTriggerAddScriptLine("return \"<icon=(\"+correctedWidth+\",\"+correctedHeight+\")(\"+icon+\")>\";");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("string minimapSafeSuffix(float posY = 0.0){");
    rmTriggerAddScriptLine("return \"\n\" + displayCompensatedIcon(1, xsFloatToInt(round((posY + 0.5) * VERTICAL_UI_PIXELS)));");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int minimapSafeDisplay(int p = 1, float x = 0.0, float y = 0.0, string content = \"\", int onTopOf = -1){");
    rmTriggerAddScriptLine("return uiSystemAddDisplay(p, x, -0.5, content + minimapSafeSuffix(y), onTopOf);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int minimapSafeDisplayWithHover(int p = 1, float x = 0.0, float y = 0.0, float width = 0.0, float height = 0.0, string content = \"\", string rolloverName = \"\", string rolloverDescription = \"\", int onTopOf = -1){");
    rmTriggerAddScriptLine("uiSystemAddDisplayWithHover(p, x, y, width, height, \"\", rolloverName, rolloverDescription);");
    rmTriggerAddScriptLine("return minimapSafeDisplay(p, x, y, content, onTopOf);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int minimapSafeClickable(int p = 1, float x = 0.0, float y = 0.0, float width = 0.0, float height = 0.0, string content = \"\", ref Parameters parameters, ");
            rmTriggerAddScriptLine("void(int, ref Parameters) handler = [](int pToUse = 1, ref Parameters parametersToUse) -> void {}, int onTopOf = -1){");
    rmTriggerAddScriptLine("uiSystemAddClickable(p, x, y, width, height, \"\", parameters, handler);");
    rmTriggerAddScriptLine("return minimapSafeDisplay(p, x, y, content, onTopOf);");
rmTriggerAddScriptLine("}");

rmTriggerAddScriptLine("int minimapSafeClickableWithHover(int p = 1, float x = 0.0, float y = 0.0, float width = 0.0, float height = 0.0, string content = \"\", string rolloverName = \"\", string rolloverDescription = \"\", ref Parameters parameters, ");
            rmTriggerAddScriptLine("void(int, ref Parameters) handler = [](int pToUse = 1, ref Parameters parametersToUse) -> void {}, int onTopOf = -1){");
    rmTriggerAddScriptLine("uiSystemAddClickableWithHover(p, x, y, width, height, \"\", rolloverName, rolloverDescription, parameters, handler);");
    rmTriggerAddScriptLine("return minimapSafeDisplay(p, x, y, content, onTopOf);");
rmTriggerAddScriptLine("}");
